name: On Push

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: iobert/content-type-converter

jobs:
  build-and-push-image:
    name: Build and push the image
    outputs:
      image-tag: ${{ steps.get-image-tag.outputs.result }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn

      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get the image tag
        uses: actions/github-script@v4
        id: get-image-tag
        with:
          script: return ${{ steps.meta.outputs.json }}.tags[0]
          result-encoding: string
